name: CI Pipeline

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Clonar o código
      uses: actions/checkout@v2

    - name: Configurar o python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Instalar as dependêcias
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        pytest

    - name: Notify on failure
      if: always()
      #if: failure()
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.gmail.com
        server_port: 587
        username: ${{ secrets.EMAIL_USERNAME }}
        password: ${{ secrets.EMAIL_PASSWORD }}
        subject: 'CI Pipeline Failed'
        body: 'Sua pipeline falhou'
        to: 'kennedyfigueiredodelima@gmail.com'
        from: 'ci-notifications@example.com'

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy para Render
      run: |
        curl -X POST ${{ secrets.URL_RENDER }}