name: CI Pipeline

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Instalar as dependêcias
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        pytest

    - name: Notify on failure
      if: always()
      #if: failure()
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.gmail.com
        server_port: 587
        username: ${{ secrets.EMAIL_USERNAME }}
        password: ${{ secrets.EMAIL_PASSWORD }}
        subject: 'CI Pipeline Failed'
        body: 'The CI pipeline failed. Please check the logs for details.'
        to: 'your-email@example.com'
        from: 'ci-notifications@example.com'

  deploy-dev: 
    runs-on: ubuntu-latest
    environment:
      name: dev
      url: 'kennedylima.com'
    needs: build
    steps:
      - name: Run a one-line script
        run: echo deploy dev
  
  deploy-homolg:
    runs-on: ubuntu-latest
    environment:
      name: homolog
      url: 'kenneyhomolog.com'
    needs: deploy-dev
    steps:
        - name: Run a one-line script
          run: echo deploy homolog     
    